### ISSUE TITLE
DNS record recreated every time

### ISSUE THREAD

**Issue by atrinchillo-mwb** [terraform-aws-modules/terraform-aws-route53#49]
## Description

Using record module, terraform recreate every-time the record name
aws_route53_zone data seems responsible of that.
It seems that it retrieves value but for terraform are like new also if you do not changed anything.

As workaroud is it possible to add a variable for the zone_id so we can pass it to the module?

**Comment by antonbabenko** [comment]
This is already supported. See the commented line in examples - https://github.com/terraform-aws-modules/terraform-aws-route53/blob/276becceadcbd5cbc0512d11cfd61cdfd9abee94/examples/complete/main.tf#L48

You need to provide either zone_id or zone_name.

**Comment by atrinchillo-mwb** [comment]
If we provide zone_id and zone_name the system complains that we can't provide both.
I tried to provide only zone_id but now terraform can try to replace always the resource also if no real changes.

This is related to
https://github.com/hashicorp/terraform-provider-aws/issues/19960


Maybe we

**Comment by atrinchillo-mwb** [comment]
HI
Is it possible to take this open? I explain why:
The problem is on data resource.
data "aws_route53_zone" "this"
When terraform use it whit zone_id OR zone_name the system want to replace the already created resource.
It is not possible to use zone_id and zone_name at the same time because the system give you an error.

To bypass this problem we should avoid creation and use of data in the case we pass zone_id and zone_name at the same time.

**Comment by yoeluk** [comment]
it looks like this issue is incorrectly closed... the issue described here is a persistent one and it is not related the the linked fix/example where the zone id for the record are fetch from a zone resource... the issue described the case when the zone id is fetch using a data source filter... no fix exists for that use case where every time that the source is read the record is replace even when the zone_id never actually changed - this is quite confusing for the use (me)

**Comment by antonbabenko** [comment]
Please open an issue according to the issue template (show code, versions, steps to reproduce, etc) which I can run and see the problem. It is very hard to do anything about issues if there are just in words.
